# PROXY
alias goproxy='export http_proxy=http://127.0.0.1:3213 https_proxy=http://127.0.0.1:3213 && echo "HTTP Proxy On"'
alias disproxy='unset http_proxy https_proxy && echo "HTTP Proxy Off"'

# SSH
alias sshzz='ssh -o TCPKeepAlive=yes -o ServerAliveInterval=30 zacky@10.214.192.51'

# MYSQL
alias mysqlll='mysql -uroot -hlocalhost -P3306 -p'
