syntax on

set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936

set nu
set magic
set noimd
set ruler
set cindent
set showcmd
set hlsearch
set incsearch
set smartcase
set autoindent
set ignorecase
set cursorline
set nowrapscan
set cursorcolumn
set nocompatible
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set signcolumn=yes
set colorcolumn=120
set list listchars=tab:»·,trail:·

set fo=trocq
set t_Co=256
set mouse=v
set laststatus=2
set ttimeoutlen=100
set backspace=indent,eol,start
set statusline=%<%f\ %m%r%h%w%{fugitive#statusline()}[TYPE=%Y]%=%-14.(%l,%c%V%)\ [%P]

" set the runtime path to include Vundle and initialize
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Programming Usage
Plugin 'L9'
"Plugin 'fcitx.vim'
Plugin 'FuzzyFinder'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'davidhalter/jedi-vim'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'klen/python-mode'
Plugin 'fatih/vim-go'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
"Plugin 'matrix.vim--Yang'
Plugin 'flazz/vim-colorschemes'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Colorscheme Settings
colorscheme jelleybeans
highlight Folded ctermbg=DarkYellow
highlight LineNr ctermbg=NONE
highlight NonText ctermbg=NONE
highlight Normal ctermbg=NONE
highlight Pmenu ctermbg=DarkYellow
highlight SignColumn ctermbg=NONE
highlight SpecialKey ctermbg=NONE
highlight StatusLineNC ctermbg=DarkMagenta
highlight SyntasticErrorSign cterm=Bold ctermfg=DarkRed ctermbg=None
highlight SyntasticWarningSign cterm=Bold ctermfg=DarkYellow ctermbg=None

au BufNewFile,BufRead *.jst,*.hbs,*.erb set filetype=html

" Keyboard Mapper
noremap  <silent> <C-y> <ESC>:w<ENTER>
nnoremap <silent> <C-j> <C-W>j<C-W>_
nnoremap <silent> <C-k> <C-W>k<C-W>_
nnoremap <silent> <C-l> <C-W>_
nnoremap <silent> cS :%s/\s\+$//g<CR>
nnoremap <silent> cM :%s/\r$//g<CR>
" Use ' To Comment Current Line
autocmd filetype cpp,java,go nnoremap <silent> ' ^i//<Esc>
autocmd filetype c nnoremap <silent> ' ^i/* <C-O>$ */<Esc>
autocmd filetype sh,python nnoremap <silent> ' ^i#<Esc>

command! -nargs=1 -bang -complete=custom,<SID>PathComplete FindInPath
      \ :find<bang> <args>
function! s:PathComplete(ArgLead, CmdLine, CursorPos)
  return UserFileComplete(a:ArgLead, a:CmdLine, a:CursorPos, 1, &path)
endfunction

" autocmd filetype python source ~/.vim/python-macros.vim
" autocmd filetype ruby source ~/.vim/ruby-macros.vim
" For JavaScript
let g:tlist_javascript_settings = 'javascript;s:string;a:array;o:object;f:function;m:member'

" Plugins Mappers
" For NERDTree
autocmd vimenter * if !argc() | NERDTree | endif
" nnoremap <C-n> :NERDTreeToggle<CR>
" nnoremap <C-n> :NERDTreeFind<CR>
" For FuzzyFinder
nnoremap <silent> fb :FufBuffer<CR>
nnoremap <silent> ff :FufFile<CR>
"nnoremap <C-t> :TlistToggle<CR>

" Plugins Settings
" For NERDTree
let NERDTreeIgnore=['\.swp$[[file]]', '\~$[[file]]']
let NERDTreeMinimalUI=1
" For Programming Language Checker
let g:pymode_options_colorcolumn=0
let g:pymode_folding=0
let g:pymode_rope=0
let g:go_fmt_fail_silently=1
" Syntax Checker
let g:syntastic_shell_checkers=['sh', 'shellcheck']
let g:syntastic_python_checkers=['python3', 'pyflakes']
let g:syntastic_go_checkers=['go', 'gofmt'] ", 'golint']
let g:syntastic_aggregate_errors=1
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_jump=0
let g:syntastic_auto_loc_list=2
let g:syntastic_check_on_open=0
let g:syntastic_check_on_wq=0
let g:syntastic_enable_highlighting=1
let g:syntastic_error_symbol = "\u2717"
let g:syntastic_warning_symbol = "\u26A0"
let g:syntastic_style_error_symbol = "S\u2717"
let g:syntastic_style_warning_symbol = "S\u26A0"

"let Tlist_GainFocus_On_ToggleOpen=1
"let Tlist_Show_One_File=1
"let Tlist_WinWidth=40
"let Tlist_Exit_OnlyWindow=1
"let Tlist_Use_Right_Window=1
"let Tlist_GainFocus_On_ToggleOpen=1
